=== measure-map/specification/measure.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://measure-map.github.io/specification/schema/1.0.1/measure.schema.json",
  "title": "Measure",
  "description": "A single measure (UK: bar) or measure-like unit of a music score.",
  "type": "object",
  "properties": {
    "ID": {
      "type": "string",
      "description": "Any unique string to identify this Measure object. Unique, here, means that the string cannot be used as ID for another object that forms part of the same MeasureMap. The 'next' array may use these IDs to refer to other Measures. Additionally, IDs can prove useful in cross-relating between MeasureMaps relating to different editions of the same piece, e.g. by assigning identical IDs for measures that are identical across the two. The ID could be, for instance, human-readable form (e.g., the 'count' value converted to a string) or a random string (often the case in MEI scores).",
      "examples": [
        "1",
        "m20",
        "var1bar6qs234",
        "https://dme.mozarteum.at/movi/navigator/155/001/01/20/nma"
      ]
    },
    "count": {
      "type": "integer",
      "minimum": 1,
      "description": "Position of this Measure object in the MeasureMap, using natural numbers starting with 1. This serves primarily as an index, and does not attempt detailed musical conventions. In the simplest case (e.g., a score with no anacrusis or other irregularities) this count matches the (most musical) number field below."
    },
    "qstamp": {
      "type": "number",
      "minimum": 0,
      "description": "The symbolic time to have elapsed since the beginning of the source, measured in quarter notes.",
      "examples": [
        0.0,
        16.5,
        20.66667
      ]
    },
    "number": {
      "type": "integer",
      "minimum": 0,
      "description": "A number assigned to this measure based on a given set of rules or conventions. One wide-spread convention, for instance, is that a piece starts with measure number 0 if it has an anacrusis and with number 1 otherwise."
    },
    "name": {
      "type": "string",
      "description": "A label for the Measure. Typically used for distinguishing between Measures with the same number, e.g. for first and second endings (as in '16a', '16b') or split logical measures (as in '16-1', '16-2').",
      "examples": [
        "1",
        "16a",
        "28-1"
      ]
    },
    "time_signature": {
      "type": "string",
      "description": "A label for the time signature. Typically this takes the form <int>/<int>, as in '3/8', but can be any text (e.g., 'C', 'common time', 'unmeasured', 'cadenza') as long as actual_length is specified.",
      "examples": [
        "3/8",
        "C",
        "cadenza"
      ]
    },
    "nominal_length": {
      "type": ["number", "null"],
      "minimum": 0,
      "description": "The default duration that corresponds to the given 'time_signature', in quarter notes. Can be derived from 'time_signature' if it takes the form of an '<int>/<int>'-encoded fraction. Can take the value 'null' if the time signature has no corresponding duration (e.g. 'cadenza').",
      "examples": [
        1.5,
        4,
        6.0,
        null
      ]
    },
    "actual_length": {
      "type": "number",
      "exclusiveMinimum": 0,
      "description": "The actual duration of the measure, in quarter notes.",
        "examples": [
            0.25,
            4,
            6.0
        ]
    },
    "start_repeat": {
      "type": [
        "boolean",
        "number"
      ],
      "default": false,
      "description": "Typical usage is with the bool type, with 'true' indicating a start repeat at the beginning of the measure."
    },
    "end_repeat": {
      "type": [
        "boolean",
        "number"
      ],
      "default": false,
      "description": "Typical usage is with the bool type, with 'true' indicating an end repeat at the end of the measure."
    },
    "volta": {
      "type": ["integer", "null"],
      "minimum": 1,
      "description": "The number of the volta (also called ending or 'prima/seconda volta' bracket) that this measure is part of, e.g. 1 for a first ending and 2 for a second ending. Takes the value 'null' if the measure is not part of a volta.",
      "examples": [
        1,
        2,
        null
      ]
    },
    "next": {
      "type": "array",
      "items": {
        "type": ["string", "integer"]
      },
      "description": "The 'ID' strings or 'count' integers that correspond to all measures that can follow this one. The corresponding field needs to be present in the MeasureMap."
    }
  },
  "anyOf": [
    {
      "properties": {
        "next": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The IDs that correspond to all measures that can follow this one."
        }
      },
      "required": [
        "ID"
      ]
    },
    {
      "properties": {
        "next": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "The counts that correspond to all measures that can follow this one."
        }
      },
      "required": [
        "count"
      ]
    }
  ],
  "additionalProperties": false
}

=== measure-map/specification/tests/valid/all_fields.json
[
  {
    "ID": "0",
    "count": 1,
    "qstamp": 0,
    "number": 0,
    "name": "0",
    "time_signature": "3/4",
    "nominal_length": 3,
    "actual_length": 1,
    "start_repeat": true,
    "end_repeat": false,
    "next": [
      "1"
    ]
  },
  {
    "ID": "1",
    "count": 2,
    "qstamp": 1,
    "number": 1,
    "name": "1",
    "time_signature": "3/4",
    "nominal_length": 3.0,
    "actual_length": 3,
    "end_repeat": true,
    "next": [
      "0",
      "2"
    ]
  },
  {
    "ID": "2",
    "count": 3,
    "qstamp": 4,
    "number": 2,
    "name": "2",
    "time_signature": "cadenza",
    "nominal_length": null,
    "actual_length": 20.66667
  }
]
